package signmaintenance;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.TimePicker;
import java.awt.Frame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JFileChooser;

/**
 *
 * @author User
 */
public class FormGUI extends javax.swing.JFrame {

    public DataIO io;
    public static File[] dirFiles;
    public CitySign sign;
    public boolean mongoDocExist;

    String dataSourceAbsPath;
    String imagesAbsPath;
    String locationsAbsPath = dataSourceAbsPath;

    // Form data fields
    public static String fileName, fileNo, lati, longi;

    /**
     * Creates new form FormGUI
     */
    public FormGUI() {
        initComponents();

        io = new DataIO();
        dirFiles = io.getImgFiles(); //file list
        dataSourceAbsPath = io.getDataSourcePath();
        imagesAbsPath = dataSourceAbsPath + "\\images";
        locationsAbsPath = dataSourceAbsPath + "\\location";
        if (dirFiles.length > 0) {
            io.openDB();
        } //files selected
        nextBtn.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        exitBtn = new javax.swing.JButton();
        SignTypeLbl = new javax.swing.JLabel();
        dateFromLbl = new javax.swing.JLabel();
        daysLbl = new javax.swing.JLabel();
        timeFromLbl = new javax.swing.JLabel();
        picNoTField = new javax.swing.JTextField();
        latitudeTField = new javax.swing.JTextField();
        longitudeTField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        pictureNoLbl = new javax.swing.JLabel();
        latitudeLbl = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        longitudeLbl = new javax.swing.JLabel();
        previousBtn = new javax.swing.JButton();
        imageLbl = new javax.swing.JLabel();
        timeToLbl = new javax.swing.JLabel();
        signTypeCBox = new javax.swing.JComboBox<>();
        maxTimeLbl = new javax.swing.JLabel();
        dateToLbl = new javax.swing.JLabel();
        dateFromPicker = new com.github.lgooddatepicker.components.DatePicker();
        dateToPicker = new com.github.lgooddatepicker.components.DatePicker();
        maxTimePicker = new com.github.lgooddatepicker.components.TimePicker();
        daysPanel = new javax.swing.JPanel();
        timeFromPicker = new com.github.lgooddatepicker.components.TimePicker();
        timeToPicker = new com.github.lgooddatepicker.components.TimePicker();
        typeAlwaysCBox = new javax.swing.JCheckBox();
        leftDirectionCBox = new javax.swing.JCheckBox();
        rightDirectionCBox = new javax.swing.JCheckBox();
        allDaysCBox = new javax.swing.JCheckBox();
        dayMondayCBox = new javax.swing.JCheckBox();
        dayTuesdayCBox = new javax.swing.JCheckBox();
        dayWednesdayCBox = new javax.swing.JCheckBox();
        dayFridayCBox = new javax.swing.JCheckBox();
        dayThursdayCBox = new javax.swing.JCheckBox();
        daySaturdayCBox = new javax.swing.JCheckBox();
        daySundayCBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Maintenance");
        setLocation(new java.awt.Point(500, 0));

        exitBtn.setText("Exit");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        SignTypeLbl.setText("Sign Type:");

        dateFromLbl.setText("Date From:");

        daysLbl.setText("Days:");

        timeFromLbl.setText("Time From:");

        picNoTField.setEditable(false);

        saveBtn.setText("Save");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        pictureNoLbl.setText("Picture Nb:");

        latitudeLbl.setText("Latitude:");

        nextBtn.setText("Next");
        nextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBtnMouseClicked(evt);
            }
        });
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        longitudeLbl.setText("Longitude:");

        previousBtn.setText("Previous");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });

        imageLbl.setToolTipText("");

        timeToLbl.setText("To:");

        signTypeCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Parking", "No Stopping", "Parking" }));
        signTypeCBox.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                signTypeCBoxCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        maxTimeLbl.setText("Max. Time:");

        dateToLbl.setText("To:");

        javax.swing.GroupLayout daysPanelLayout = new javax.swing.GroupLayout(daysPanel);
        daysPanel.setLayout(daysPanelLayout);
        daysPanelLayout.setHorizontalGroup(
            daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        daysPanelLayout.setVerticalGroup(
            daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        timeFromPicker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timeFromPickerMouseExited(evt);
            }
        });
        timeFromPicker.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                timeFromPickerCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        timeFromPicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                timeFromPickerPropertyChange(evt);
            }
        });

        timeToPicker.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                timeToPickerCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        typeAlwaysCBox.setText("Always");
        typeAlwaysCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeAlwaysCBoxActionPerformed(evt);
            }
        });

        leftDirectionCBox.setText("Left Direction");
        leftDirectionCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDirectionCBoxActionPerformed(evt);
            }
        });

        rightDirectionCBox.setText("Right Direction");
        rightDirectionCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDirectionCBoxActionPerformed(evt);
            }
        });

        allDaysCBox.setText("All Days");
        allDaysCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allDaysCBoxActionPerformed(evt);
            }
        });

        dayMondayCBox.setText("Monday");
        dayMondayCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayMondayCBoxActionPerformed(evt);
            }
        });

        dayTuesdayCBox.setText("Tuesday");
        dayTuesdayCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTuesdayCBoxActionPerformed(evt);
            }
        });

        dayWednesdayCBox.setText("Wednesday");
        dayWednesdayCBox.setMaximumSize(new java.awt.Dimension(67, 23));
        dayWednesdayCBox.setMinimumSize(new java.awt.Dimension(67, 23));
        dayWednesdayCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayWednesdayCBoxActionPerformed(evt);
            }
        });

        dayFridayCBox.setText("Friday");
        dayFridayCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayFridayCBoxActionPerformed(evt);
            }
        });

        dayThursdayCBox.setText("Thursday");
        dayThursdayCBox.setMaximumSize(new java.awt.Dimension(67, 23));
        dayThursdayCBox.setMinimumSize(new java.awt.Dimension(67, 23));
        dayThursdayCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayThursdayCBoxActionPerformed(evt);
            }
        });

        daySaturdayCBox.setText("Saturday");
        daySaturdayCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daySaturdayCBoxActionPerformed(evt);
            }
        });

        daySundayCBox.setText("Sunday");
        daySundayCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daySundayCBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pictureNoLbl)
                                    .addComponent(latitudeLbl)
                                    .addComponent(longitudeLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(longitudeTField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(picNoTField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(latitudeTField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateFromLbl)
                                    .addComponent(dateToLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateToPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateFromPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(timeFromLbl)
                                    .addComponent(maxTimeLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(timeFromPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(timeToLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(timeToPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(maxTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(daysLbl)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dayFridayCBox)
                                            .addComponent(dayWednesdayCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(dayThursdayCBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dayMondayCBox)
                                                        .addComponent(dayTuesdayCBox))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(daySundayCBox)
                                                        .addComponent(daySaturdayCBox))))
                                            .addComponent(allDaysCBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(daysPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SignTypeLbl)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(signTypeCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(typeAlwaysCBox)
                                            .addComponent(leftDirectionCBox)
                                            .addComponent(rightDirectionCBox))))))
                        .addGap(18, 18, 18)
                        .addComponent(imageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitBtn)
                .addGap(34, 34, 34))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nextBtn, previousBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dayFridayCBox, dayMondayCBox, daySaturdayCBox, daySundayCBox, dayThursdayCBox, dayTuesdayCBox, dayWednesdayCBox});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pictureNoLbl)
                            .addComponent(picNoTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(latitudeLbl)
                            .addComponent(latitudeTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(longitudeLbl)
                            .addComponent(longitudeTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SignTypeLbl)
                            .addComponent(signTypeCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeAlwaysCBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leftDirectionCBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightDirectionCBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(allDaysCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(daysLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dayTuesdayCBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(daySaturdayCBox)
                                            .addComponent(dayMondayCBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(daySundayCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)
                                .addComponent(dayWednesdayCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayThursdayCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayFridayCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(daysPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeFromLbl)
                            .addComponent(timeToLbl)
                            .addComponent(timeFromPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeToPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxTimeLbl)
                            .addComponent(maxTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateFromLbl)
                            .addComponent(dateFromPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateToLbl)
                            .addComponent(dateToPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(exitBtn)
                    .addComponent(previousBtn)
                    .addComponent(nextBtn))
                .addGap(43, 43, 43))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dayFridayCBox, daySaturdayCBox, daySundayCBox, dayThursdayCBox, dayTuesdayCBox, dayWednesdayCBox});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {maxTimeLbl, maxTimePicker, timeFromLbl});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processImgFile(String curImgFileName) {

        sign = io.getImageInfo(curImgFileName);
        //resize image
        String inputImagePath = imagesAbsPath + "\\" + curImgFileName;
        String outputImagePath = dataSourceAbsPath + "\\" + "resizeTemp.jpg";
        try {
            double percent = 0.2;
            ImageResizer.resize(inputImagePath, outputImagePath, percent);
        } catch (IOException ex) {
            System.out.println("Error resizing image: " + inputImagePath);
        }
        // update image on screen using ImageIO
        try {
            imageLbl.setIcon(new ImageIcon(ImageIO.read(new File(outputImagePath))));
        } catch (IOException e) {
            e.printStackTrace();
        }
        // update screen for mongo Key Fields
        picNoTField.setText(sign.pf.fileNo);
        latitudeTField.setText(sign.latitude);
        longitudeTField.setText(sign.longitude);
        // check if exist in mongo
        mongoDocExist = io.getMongoDoc(sign);
        if (mongoDocExist) {
            signTypeCBox.setSelectedItem(sign.type);
            // update regular screen fields
            typeAlwaysCBox.setSelected(sign.typeAlways);
            leftDirectionCBox.setSelected(sign.leftDirection);
            rightDirectionCBox.setSelected(sign.rightDirection);
            allDaysCBox.setSelected(sign.allDays);
            daySundayCBox.setSelected(sign.days[0]);
            dayMondayCBox.setSelected(sign.days[1]);
            dayTuesdayCBox.setSelected(sign.days[2]);
            dayWednesdayCBox.setSelected(sign.days[3]);
            dayThursdayCBox.setSelected(sign.days[4]);
            dayFridayCBox.setSelected(sign.days[5]);
            daySaturdayCBox.setSelected(sign.days[6]);
            timeFromPicker.setText(sign.timeFrom);
            timeToPicker.setText(sign.timeTo);
            dateFromPicker.setText(sign.dateFrom);
            dateToPicker.setText(sign.dateTo);
        }
    }

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        //DataIO.closeDB();
        //System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        DataIO.closeDB();
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // validate fields
        // Save mongo document
        //DataIO.saveToMongo();
        // load next file or quit app
    }//GEN-LAST:event_saveBtnMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // validate fields
        // determine icon
        String signIcon = null;
        switch (sign.type) {
            case "NoParking":
                if (sign.typeAlways) {
                    signIcon = "images/NoParkingAlways.png";
                    if (sign.leftDirection) {
                        signIcon = "images/NoParkingLeftDirection.png";
                    }
                    if (sign.rightDirection) {
                        signIcon = "images/NoParkingRightDirection.png";
                    }
                    if (sign.rightDirection && sign.leftDirection) {
                        signIcon = "images/NoParkingBothDirection.png";
                    }
                } else {
                    signIcon = "images/NoParkingTimeRestriction.png";
                }
                break;
            case "NoStopping":
                if (sign.typeAlways) {
                    signIcon = "images/NoStoppingAlways.png";
                    if (sign.leftDirection) {
                        signIcon = "images/NoStoppingLeftDirection.png";
                    }
                    if (sign.rightDirection) {
                        signIcon = "images/NoStoppingRightDirection.png";
                    }
                    if (sign.rightDirection && sign.leftDirection) {
                        signIcon = "images/NoStoppingBothDirection.png";
                    }
                } else {
                    signIcon = "images/NoStoppingTimeRestriction.png";
                }
                break;
            case "Parking":
                if (sign.typeAlways) {
                    signIcon = "images/ParkingAlways.png";
                    if (sign.leftDirection) {
                        signIcon = "images/ParkingLeftDirection.png";
                    }
                    if (sign.rightDirection) {
                        signIcon = "images/ParkingRightDirection.png";
                    }
                    if (sign.rightDirection && sign.leftDirection) {
                        signIcon = "images/ParkingBothDirection.png";
                    }
                } else {
                    signIcon = "images/ParkingTimeRestriction.png";
                }
                break;
            default:
                signIcon = null;
                break;
        } //switch

        // set Sign data
        sign.type = signTypeCBox.getSelectedItem().toString(); //set default value 
        sign.icon = signIcon;
        sign.typeAlways = typeAlwaysCBox.isSelected();
        sign.leftDirection = leftDirectionCBox.isSelected();
        sign.rightDirection = rightDirectionCBox.isSelected();
        sign.allDays = allDaysCBox.isSelected();
        sign.days[0] = daySundayCBox.isSelected();
        sign.days[1] = dayMondayCBox.isSelected();
        sign.days[2] = dayTuesdayCBox.isSelected();
        sign.days[3] = dayWednesdayCBox.isSelected();
        sign.days[4] = dayThursdayCBox.isSelected();
        sign.days[5] = dayFridayCBox.isSelected();
        sign.days[6] = daySaturdayCBox.isSelected();
        sign.timeFrom = timeFromPicker.getTimeStringOrEmptyString();
        sign.timeTo = timeToPicker.getTimeStringOrEmptyString();
        sign.maxTime = maxTimePicker.getTimeStringOrEmptyString();
        sign.dateFrom = dateFromPicker.getDateStringOrEmptyString();
        sign.dateTo = dateToPicker.getDateStringOrEmptyString();

        // Save mongo document
        if (mongoDocExist) {
            //io.insertToMongo(sign);
        } else {
            io.saveToMongo(sign);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TO DO reset previous values of TFields
        // get next sign image
        processImgFile(io.getNextImg(dirFiles));
    }//GEN-LAST:event_nextBtnActionPerformed

    private void nextBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseClicked
        // TO DO check for data fields change and confirm loss to go next
    }//GEN-LAST:event_nextBtnMouseClicked

    private void dayTuesdayCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTuesdayCBoxActionPerformed
        // TODO add your handling code here:
        sign.days[2] = dayTuesdayCBox.isSelected();
    }//GEN-LAST:event_dayTuesdayCBoxActionPerformed

    private void dayWednesdayCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayWednesdayCBoxActionPerformed
        // TODO add your handling code here:
        sign.days[3] = dayWednesdayCBox.isSelected();
    }//GEN-LAST:event_dayWednesdayCBoxActionPerformed

    private void dayFridayCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayFridayCBoxActionPerformed
        // TODO add your handling code here:
        sign.days[5] = dayFridayCBox.isSelected();
    }//GEN-LAST:event_dayFridayCBoxActionPerformed

    private void daySundayCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daySundayCBoxActionPerformed
        // TODO add your handling code here:
        sign.days[0] = daySundayCBox.isSelected();
    }//GEN-LAST:event_daySundayCBoxActionPerformed

    private void dayThursdayCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayThursdayCBoxActionPerformed
        // TODO add your handling code here:
        sign.days[4] = dayThursdayCBox.isSelected();
    }//GEN-LAST:event_dayThursdayCBoxActionPerformed

    private void daySaturdayCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daySaturdayCBoxActionPerformed
        // TODO add your handling code here:
        sign.days[6] = daySaturdayCBox.isSelected();
    }//GEN-LAST:event_daySaturdayCBoxActionPerformed

    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        // TO DO check for data fields change and confirm loss to go next
        // TO DO reset previous values of TFields
        // get revious sign image
        processImgFile(io.getPreviousImg(dirFiles));
    }//GEN-LAST:event_previousBtnActionPerformed

    private void signTypeCBoxCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_signTypeCBoxCaretPositionChanged
        // TODO add your handling code here:
        sign.type = signTypeCBox.getSelectedItem().toString();
    }//GEN-LAST:event_signTypeCBoxCaretPositionChanged

    private void timeFromPickerCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_timeFromPickerCaretPositionChanged
        // TODO add your handling code here:
        //.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        sign.timeFrom = timeFromPicker.getText();
    }//GEN-LAST:event_timeFromPickerCaretPositionChanged

    private void timeFromPickerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeFromPickerMouseExited
        // TODO add your handling code here:
        //sign.timeFrom = timeFromPicker.toString();
    }//GEN-LAST:event_timeFromPickerMouseExited

    private void timeFromPickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_timeFromPickerPropertyChange
        // TODO add your handling code here:
        //sign.timeFrom = timeFromPicker.toString();
    }//GEN-LAST:event_timeFromPickerPropertyChange

    private void timeToPickerCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_timeToPickerCaretPositionChanged
        // TODO add your handling code here:
        sign.timeTo = timeToPicker.getText();
    }//GEN-LAST:event_timeToPickerCaretPositionChanged

    private void typeAlwaysCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeAlwaysCBoxActionPerformed
        sign.typeAlways = typeAlwaysCBox.isSelected();
    }//GEN-LAST:event_typeAlwaysCBoxActionPerformed

    private void dayMondayCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayMondayCBoxActionPerformed
        sign.days[1] = dayMondayCBox.isSelected();
    }//GEN-LAST:event_dayMondayCBoxActionPerformed

    private void leftDirectionCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDirectionCBoxActionPerformed
        sign.leftDirection = leftDirectionCBox.isSelected();
    }//GEN-LAST:event_leftDirectionCBoxActionPerformed

    private void rightDirectionCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDirectionCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightDirectionCBoxActionPerformed

    private void allDaysCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allDaysCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allDaysCBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignTypeLbl;
    private javax.swing.JCheckBox allDaysCBox;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private javax.swing.JLabel dateFromLbl;
    private com.github.lgooddatepicker.components.DatePicker dateFromPicker;
    private javax.swing.JLabel dateToLbl;
    private com.github.lgooddatepicker.components.DatePicker dateToPicker;
    private javax.swing.JCheckBox dayFridayCBox;
    private javax.swing.JCheckBox dayMondayCBox;
    private javax.swing.JCheckBox daySaturdayCBox;
    private javax.swing.JCheckBox daySundayCBox;
    private javax.swing.JCheckBox dayThursdayCBox;
    private javax.swing.JCheckBox dayTuesdayCBox;
    private javax.swing.JCheckBox dayWednesdayCBox;
    private javax.swing.JLabel daysLbl;
    private javax.swing.JPanel daysPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel latitudeLbl;
    private javax.swing.JTextField latitudeTField;
    private javax.swing.JCheckBox leftDirectionCBox;
    private javax.swing.JLabel longitudeLbl;
    private javax.swing.JTextField longitudeTField;
    private javax.swing.JLabel maxTimeLbl;
    private com.github.lgooddatepicker.components.TimePicker maxTimePicker;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField picNoTField;
    private javax.swing.JLabel pictureNoLbl;
    private javax.swing.JButton previousBtn;
    private javax.swing.JCheckBox rightDirectionCBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> signTypeCBox;
    private javax.swing.JLabel timeFromLbl;
    private com.github.lgooddatepicker.components.TimePicker timeFromPicker;
    private javax.swing.JLabel timeToLbl;
    private com.github.lgooddatepicker.components.TimePicker timeToPicker;
    private javax.swing.JCheckBox typeAlwaysCBox;
    // End of variables declaration//GEN-END:variables
}
